FROM node:20-alpine AS builder

WORKDIR /app
RUN apk add --no-cache python3 make g++
COPY shared ./shared

WORKDIR /app/realtime-gateway
COPY realtime-gateway/package*.json ./
RUN npm ci
COPY realtime-gateway ./
RUN npm run build

#======================================================
FROM node:20-alpine AS runner

WORKDIR /app/realtime-gateway
COPY realtime-gateway/package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/realtime-gateway/dist ./dist

USER node
CMD ["node", "dist/main.js"]
