FROM node:20-alpine AS builder

WORKDIR /app
RUN apk add --no-cache python3 make g++
COPY shared ./shared

WORKDIR /app/games
COPY games/package*.json ./
RUN npm ci
COPY games ./
RUN npm run build

#======================================================
FROM node:20-alpine AS runner

WORKDIR /app/games
COPY games/package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/games/dist ./dist

USER node
CMD ["node", "dist/main.js"]
