FROM node:20-alpine AS deps

WORKDIR /app/front
RUN apk add --no-cache libc6-compat
COPY front/package*.json ./
RUN npm ci

#======================================================
FROM node:20-alpine AS builder

WORKDIR /app/front
COPY --from=deps /app/front/node_modules ./node_modules
COPY front ./

WORKDIR /app
COPY shared ./shared

WORKDIR /app/front
RUN npm run build

#======================================================
FROM node:20-alpine AS runner

WORKDIR /app/front
COPY --from=deps /app/front/package*.json ./
COPY --from=deps /app/front/node_modules ./node_modules
COPY --from=builder /app/front/.next ./.next
COPY --from=builder /app/front/public ./public

USER node
CMD ["npm", "run", "start"]
