FROM nginx:alpine

RUN apk add --no-cache openssl \
	&& mkdir -p /etc/nginx/ssl \
	&& openssl req -x509 -nodes -days 365 \
		-newkey rsa:2048 \
		-subj "/CN=localhost" \
		-keyout /etc/nginx/ssl/selfsigned.key \
		-out /etc/nginx/ssl/selfsigned.crt

# Use nginx.conf as a template for /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/templates/default.conf.template

