FROM nginx:alpine

# Copy nginx configuration into the image
COPY nginx.conf /etc/nginx/nginx.conf

RUN apk add --no-cache openssl \
	&& mkdir -p /etc/nginx/ssl \
	&& openssl req -x509 -nodes -days 365 \
		-newkey rsa:2048 \
		-subj "/CN=localhost" \
		-keyout /etc/nginx/ssl/selfsigned.key \
		-out /etc/nginx/ssl/selfsigned.crt


